# Generated by Django 4.1.5 on 2023-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200, null=True, verbose_name='Employee Name')),
                ('emp_id', models.CharField(max_length=200, null=True, verbose_name='Employee ID')),
                ('emp_add', models.CharField(max_length=800, null=True, verbose_name='Employee Address')),
                ('emp_ad_img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
