# Generated by Django 4.1.5 on 2023-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_employee_emp_ad_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_ad_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
